/**
 * Generated by @kubb/plugin-zod - Do not edit by hand
 * @see https://github.com/kubb-labs/kubb/tree/main/packages/plugin-zod
 */

import { applicationSchema } from './applicationSchema.ts'
import { errorSchema } from './errorSchema.ts'
import { notAuthorizedErrorSchema } from './notAuthorizedErrorSchema.ts'
import { z } from 'zod'

/**
 * @description The request has succeeded.
 */
export const applicationsList200Schema = z.array(z.lazy(() => applicationSchema))

export type ApplicationsList200Schema = z.infer<typeof applicationsList200Schema>

/**
 * @description Access is unauthorized.
 */
export const applicationsList401Schema = z.lazy(() => notAuthorizedErrorSchema)

export type ApplicationsList401Schema = z.infer<typeof applicationsList401Schema>

/**
 * @description Server error
 */
export const applicationsList500Schema = z.lazy(() => errorSchema)

export type ApplicationsList500Schema = z.infer<typeof applicationsList500Schema>

export const applicationsListQueryResponseSchema = z.lazy(() => applicationsList200Schema)

export type ApplicationsListQueryResponseSchema = z.infer<typeof applicationsListQueryResponseSchema>