/**
 * Generated by @kubb/plugin-zod - Do not edit by hand
 * @see https://github.com/kubb-labs/kubb/tree/main/packages/plugin-zod
 */

import { applicationCreateSchema } from './applicationCreateSchema.ts'
import { applicationSchema } from './applicationSchema.ts'
import { badRequestErrorSchema } from './badRequestErrorSchema.ts'
import { errorSchema } from './errorSchema.ts'
import { notAuthorizedErrorSchema } from './notAuthorizedErrorSchema.ts'
import { z } from 'zod'

/**
 * @description The request has succeeded.
 */
export const applicationsCreate200Schema = z.lazy(() => applicationSchema)

export type ApplicationsCreate200Schema = z.infer<typeof applicationsCreate200Schema>

/**
 * @description The server could not understand the request due to invalid syntax.
 */
export const applicationsCreate400Schema = z.lazy(() => badRequestErrorSchema)

export type ApplicationsCreate400Schema = z.infer<typeof applicationsCreate400Schema>

/**
 * @description Access is unauthorized.
 */
export const applicationsCreate401Schema = z.lazy(() => notAuthorizedErrorSchema)

export type ApplicationsCreate401Schema = z.infer<typeof applicationsCreate401Schema>

/**
 * @description Server error
 */
export const applicationsCreate500Schema = z.lazy(() => errorSchema)

export type ApplicationsCreate500Schema = z.infer<typeof applicationsCreate500Schema>

export const applicationsCreateMutationRequestSchema = z.lazy(() => applicationCreateSchema)

export type ApplicationsCreateMutationRequestSchema = z.infer<typeof applicationsCreateMutationRequestSchema>

export const applicationsCreateMutationResponseSchema = z.lazy(() => applicationsCreate200Schema)

export type ApplicationsCreateMutationResponseSchema = z.infer<typeof applicationsCreateMutationResponseSchema>