/**
 * Generated by @kubb/plugin-zod - Do not edit by hand
 * @see https://github.com/kubb-labs/kubb/tree/main/packages/plugin-zod
 */

import { z } from 'zod'

export const clientSecretCreateSchema = z.object({
  description: z.string().describe('The secret name'),
  value: z.string().describe('The secret value, masked when read'),
})

export type ClientSecretCreateSchema = z.infer<typeof clientSecretCreateSchema>