/**
 * Generated by @kubb/plugin-zod - Do not edit by hand
 * @see https://github.com/kubb-labs/kubb/tree/main/packages/plugin-zod
 */

import { z } from 'zod'

export const errorDetailSchema = z.object({
  key: z.string(),
  message: z.string(),
})

export type ErrorDetailSchema = z.infer<typeof errorDetailSchema>