import { defineConfig } from '@kubb/core';
import { pluginZod } from '@kubb/plugin-zod';
import { pluginOas } from '@kubb/plugin-oas';

const banner = `/**
 * Generated by @kubb/plugin-zod - Do not edit by hand
 * @see https://github.com/kubb-labs/kubb/tree/main/packages/plugin-zod
 */
`;

export default defineConfig({
  input: {
    path: './src/openapi.json',
  },
  output: {
    path: './src/schema',
  },
  plugins: [
    pluginOas({ output: false as any }),
    pluginZod({
      inferred: true,
      output: {
        path: './zod',
        banner,
      },
    }),
  ],
});
